### ISSUE TITLE
Build cli that other project can run to generate sdk

### ISSUE THREAD

**Issue by paibamboo** [crazyfactory/tinka-generator-openapi#1]
The other project will use it in package.json like this
`"scripts": "tinka-generator-openapi --spec schema/spec.json --project shop-api"`

EDIT: changed to
`"scripts": "tinka-generator-openapi --spec schema/spec.json --lang typescript"`

**Comment by wmathes** [comment]
What does the 'project' parameter do exactly? :)

**Comment by paibamboo** [comment]
-- project is changed to --lang to specify what language should it be converted into.

**Comment by paibamboo** [comment]
This was done.
