### ISSUE TITLE
Take account for basic auth endpoint

### ISSUE THREAD

**Issue by paibamboo** [crazyfactory/tinka-generator-openapi#29]
Logging in using the current sdk is inconvenient. The convention for logging in is to be put in the header like so `{"Authorization": "Basic " + base64<username + password>}`. But our current login function accepts nothing. Although we can pass this as an option parameter like below
```typescript
shopService.auth.authentication({
  headers: { Authorization: "Basic " + btoa("admin@example.com:1234")}
});
```
, it's much better to just to just do
```typescript
shopService.auth.authentication("admin@example.com", "1234");
```

**Comment by wmathes** [comment]
uhm please provide a description that other people can understand as well :)

**Comment by paibamboo** [comment]
Logging in using the current sdk is inconvenient. The convention for logging in is to be put in the header like so `{"Authorization": "Basic " + base64<username + password>}`. But our current login function accepts nothing. Although we can pass this as an option parameter like below
```typescript
shopService.auth.authentication({
  headers: { Authorization: "Basic " + btoa("admin@example.com:1234")}
});
```
, it's much better to just to just do
```typescript
shopService.auth.authentication("admin@example.com", "1234");
```
